name: Cache

on:
  push:

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: LigneCore                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: LigneCoreTest                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      Wap_Project_Directory: your-wap-project-directory-name    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Wap_Project_Path: your-wap-project-path                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Create a text file containing a random string
    - name: Create a text file containing a random string
      id: random-string
      run: |
        echo ${{ github.run_id }} > random.txt
        echo ${{ github.run_id }} > random2.txt

    # Save the random string to the cache    
    - uses: actions/cache/save@v3
      with:
        path: .
        key: cache
        enableCrossOsArchive: true

  release-please:
    permissions:
      contents: write
      packages: write
      pull-requests: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v3
        with:
          path: .
          key: cache
          enableCrossOsArchive: true

      - name: Run
        run: |
          cat random.txt
          cat random2.txt
